name: gamePhaserCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: go
        run: |
          git config  user.name "runoob"
          git config  user.email test@runoob.com
          cd joystickHHH
          unzip example.zip
          git config --list
          git push origin main
