name: gamePhaserCI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: go
        run: |
          ls
          cd joystickHHH
          unzip example.zip
          git push
          
